#!/bin/bash

## Description: import given test data into ddev (database and configurations)
## Usage: initialize
## Example: "ddev initialize"

mkdir -p config/sites/main
ln -snf ../../../.ddev/TYPO3/config.yaml config/sites/main/config.yaml
mkdir -p config/system
ln -snf ../../.ddev/TYPO3/settings.php config/system/settings.php
ln -snf ../../.ddev/TYPO3/additional.php config/system/additional.php
mkdir -p .Build/public/fileadmin

echo "Importing database"
ddev import-db --file=.ddev/data/db.sql.gz

echo "Run 'composer install'"
ddev composer install

echo "Copy .htaccess"
cp .Build/vendor/typo3/cms-install/Resources/Private/FolderStructureTemplateFiles/root-htaccess .Build/public/.htaccess
